# This is a basic workflow to help you get started with Actions

name: Linux Workflow

# Controls when the workflow will run
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Download and unzip
        run: 
        wget https://github.com/michaelp3/linux/archive/$GITHUB_SHA.zip -o file.zip
        unzip ./file.zip
    
